#took help from: https://github.com/docker/awesome-compose
version: '3.8'

# https://stackoverflow.com/questions/75246059/create-a-postgres-database-within-a-docker-compose-yml-file
services:
  db:
    image: postgres
    restart: always
    networks:
      - bkd-net
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    # depends_on:
    #   - db
  # server:
  #   networks:
  #     - bkd-net
    
networks:
  bkd-net: {}

volumes:
  db-data: {}